### ISSUE TITLE
Token Creation for WLAN AP failed

### ISSUE THREAD

**Issue by maxhro** [iobroker-community-adapters/ioBroker.hmip#207]
Hello, 

cannot create an Access Token for the new HMIP WLAN-HAP. With the old LAN AP no problems. Is this device not yet supported?

  |   |   |  
-- | -- | -- | --
hmip.0 | 2020-12-25 18:01:14.010 | error | (442456) error requesting token: error
hmip.0 | 2020-12-25 18:01:14.009 | warn | (442456) Request error: RequestError: Error: Invalid URI "/hmip/auth/connectionRequest"
hmip.0 | 2020-12-25 18:01:14.008 | info | (442456) auth step 1
hmip.0 | 2020-12-25 18:01:14.007 | warn | (442456) Request error: StatusCodeError: 418 - {"errorCode":"INVALID_REQUEST"}
hmip.0 | 2020-12-25 18:01:13.889 | info | (442456) started token request

**Comment by Apollon77** [comment]
Closed because?

**Comment by moritzhub** [comment]
I get this error too and would be very interested in the solution.

**Comment by moritzhub** [comment]
@Apollon77 I think I found the issue.

getHomematicHosts() fails with INVALID_REQUEST if the SGTIN of the AP is incorrect. That leaves _urlREST unset.
https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/6c6f2029f3a9e463b22e36399eb17cea8082c6f1/api/hm-cloud-api.js#L66

As result, auth1connectionRequest() fails because _urlREST is not set and hence the concatenated API URL is incomplete.
https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/6c6f2029f3a9e463b22e36399eb17cea8082c6f1/api/hm-cloud-api.js#L92

**Comment by maxhro** [comment]
> Closed because?

Sorry for the late answer. It was a simple fault on my side. Inserting 8 instead B as part of the  SGTIN Code. Was a little difficult to read the code

**Comment by Apollon77** [comment]
@moritzhub ok, next version will check that
