### ISSUE TITLE
HmIP-HCU1 support

### ISSUE THREAD

**Issue by KristianHeider** [iobroker-community-adapters/ioBroker.hmip#589]
Is there any support planned?

Today I received the new HCU. On pressing "Token erstellen" and press head button on HCU for confirmation there is a wheel of no return on configuration page. Unfortunatly there is no access.

iobroker.hmip version v1.24.3

**Comment by nodesupport1** [comment]
@KristianHeider It seems like you're experiencing difficulties with the configuration process on the new HCU. The "wheel of no return" issue you're facing might be due to a technical glitch or a misconfiguration.It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID HCU07638
Please see the link below to our dedicated support line:
[HCU Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Apollon77** [comment]
Lets phrase it that way ... we do not know because we do not have such a device yet and we do not know what was changed and all of this ...

**Comment by mcm1957** [comment]
added with 1.26.0
